name: linux/mac

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    env:
      CC: ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler:
        - gcc
        - clang
        os:
        - ubuntu-latest
        - macOS-latest

    steps:
    - uses: actions/checkout@v2

    - run: env | sort
    - name: Install software
      if: ${{ matrix.os == 'macOS-latest' }}
      run: |
        brew install automake bash coreutils make
        echo "/usr/local/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
        echo "/usr/local/opt/make/libexec/gnubin" >> $GITHUB_PATH
    - name: Fetch branches
      run: |
        git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        git fetch --unshallow

    - run: ./bootstrap
    - run: ./configure
    - run: make
    - run: make test-all

    - run: |
        git clean -d -x -f
        rm -fr tests/run-test-suite
        git worktree prune

    - name: Compiler version
      run: ${{ matrix.compiler }} --version
    - run: cmake .
    - run: make
    - run: make test
