version: 2
jobs:
  build:
    docker:
      - image: ossrs/dev
    steps:
      - checkout
      - cd trunk && ./configure --without-ssl --without-valgrind && make
  test:
    docker:
      - image: ossrs/dev
    steps:
      - checkout
      - cd trunk && ./configure --without-ssl --without-valgrind && make && ./objs/srs_utest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

