version: 2
jobs:
  build:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: cd trunk && ./configure && make
  test:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: cd trunk && ./configure --gcov && make && ./objs/srs_utest && bash auto/coverage.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

